#!/usr/bin/env python3
"""End-to-end controller input test for mesen-mcp.

The smoke test only checks that set_controller returns without an error - this
test checks that the buttons actually reach the *emulated game*.

NES: the fixture ROM (input-test.nes, generated by make_input_test_rom.py) polls
$4016/$4017 in a loop and stores what it read at $00F0/$00F1, so every check
below goes through the game's own joypad code:

    bit 0 = A      bit 2 = Select   bit 4 = Up     bit 6 = Left
    bit 1 = B      bit 3 = Start    bit 5 = Down   bit 7 = Right

SNES / GBA: the controller state is read back with the Lua API
(emu.getInput), which returns the control device state the console's own
input polling uses.

Usage: input_test.py [path-to-mesen-mcp]   (default: bin/mesen-mcp)
"""
import base64
import json
import os
import re
import shutil
import subprocess
import sys

TESTS = os.path.dirname(os.path.abspath(__file__))
BIN = sys.argv[1] if len(sys.argv) > 1 else os.path.join("bin", "mesen-mcp")
HOME = os.path.join(TESTS, "input-home")
NES_ROM = os.path.join(TESTS, "input-test.nes")

sys.path.insert(0, TESTS)
import make_input_test_rom  # noqa: E402  (fixture ROM generator)

passed = 0


def ok(name, cond, detail=""):
    global passed
    if not cond:
        print(f"  FAIL: {name} {detail}")
        sys.exit(1)
    passed += 1
    print(f"  ok: {name}")


class Client:
    def __init__(self):
        env = dict(os.environ, ASAN_OPTIONS="detect_leaks=0")
        self.proc = subprocess.Popen(
            [BIN, "--home", HOME], stdin=subprocess.PIPE, stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL, env=env, text=True, bufsize=1)
        self._id = 0

    def request(self, method, params=None):
        self._id += 1
        self.proc.stdin.write(json.dumps({
            "jsonrpc": "2.0", "id": self._id, "method": method,
            **({"params": params} if params is not None else {})}) + "\n")
        self.proc.stdin.flush()
        line = self.proc.stdout.readline()
        if not line:
            raise RuntimeError(f"server died (rc={self.proc.poll()}) during {method}")
        return json.loads(line)

    def tool(self, name, args=None):
        r = self.request("tools/call", {"name": name, "arguments": args or {}})
        if r["result"]["isError"]:
            return {"ERR": r["result"]["content"][0]["text"]}
        d = {}
        for c in r["result"]["content"]:
            if c["type"] == "text":
                try:
                    d = json.loads(c["text"])
                except json.JSONDecodeError:
                    d = {"text": c["text"]}
            elif c["type"] == "image":
                d["_png"] = base64.b64decode(c["data"])
        return d

    def close(self):
        self.proc.stdin.close()
        return self.proc.wait(timeout=20)


def initialize(c):
    r = c.request("initialize", {"protocolVersion": "2025-06-18",
                                 "clientInfo": {"name": "input-test", "version": "0"}})
    ok("initialize", r["result"]["serverInfo"]["name"] == "mesen-mcp")


def joypad_bytes(c):
    """$00F0 (port 1) / $00F1 (port 2) / $00F2 (poll counter), as read by the ROM."""
    d = c.tool("read_memory", {"memory_type": "internal_ram", "address": 0xF0, "length": 3})
    if "ERR" in d:
        raise RuntimeError(d["ERR"])
    return d["bytes"]


def read_byte(c, addr):
    d = c.tool("read_memory", {"memory_type": "internal_ram", "address": addr, "length": 1})
    if "ERR" in d:
        raise RuntimeError(d["ERR"])
    return d["bytes"][0]


def lua_pressed(c, port0):
    """Buttons the console reports as pressed on a 0-based port, via the Lua API."""
    code = (f"local t = emu.getInput(0, {port0}); local s = '';"
            "for k, v in pairs(t) do if v then s = s .. k .. ',' end end; print('BTN=' .. s)")
    d = c.tool("run_lua_script", {"code": code})
    if "ERR" in d:
        raise RuntimeError(d["ERR"])
    m = re.search(r"BTN=([A-Za-z,]*)", d.get("log", ""))
    if not m:
        raise RuntimeError("lua getInput produced no output: " + repr(d)[:200])
    return {tok for tok in m.group(1).split(",") if tok}


def nes_battery():
    print("\n== NES fixture ROM (game reads $4016/$4017 itself) ==")
    c = Client()
    try:
        initialize(c)
        ld = c.tool("load_rom", {"path": NES_ROM})
        ok("load fixture rom", "ERR" not in ld, str(ld)[:160])
        run = c.tool("run_frames", {"frames": 10, "timeout_ms": 15000})
        ok("run_frames", run.get("frames_run", 0) >= 10, str(run)[:120])

        p1, p2, polls = joypad_bytes(c)
        ok("rom is polling the joypad", polls > 0, f"$00F2={polls}")
        ok("no buttons pressed initially", p1 == 0 and p2 == 0, f"p1=${p1:02X} p2=${p2:02X}")

        #Buttons held until changed
        r = c.tool("set_controller", {"port": 1, "buttons": ["a"]})
        ok("set_controller a", "ERR" not in r, str(r)[:160])
        c.tool("run_frames", {"frames": 5, "timeout_ms": 15000})
        p1, p2, _ = joypad_bytes(c)
        ok("game sees A", p1 == 0x01, f"$00F0=${p1:02X} (expected $01)")

        #Still held after many frames (no auto-release)
        c.tool("run_frames", {"frames": 30, "timeout_ms": 15000})
        p1, _, _ = joypad_bytes(c)
        ok("A still held after 30 frames", p1 == 0x01, f"$00F0=${p1:02X}")

        #Changing the button set replaces the previous one
        c.tool("set_controller", {"port": 1, "buttons": "start,up"})
        c.tool("run_frames", {"frames": 5, "timeout_ms": 15000})
        p1, _, _ = joypad_bytes(c)
        ok("game sees Start+Up (string form)", p1 == 0x18, f"$00F0=${p1:02X} (expected $18)")

        #All eight buttons
        c.tool("set_controller", {"port": 1, "buttons":
                                  ["a", "b", "select", "start", "up", "down", "left", "right"]})
        c.tool("run_frames", {"frames": 5, "timeout_ms": 15000})
        p1, _, _ = joypad_bytes(c)
        ok("game sees all 8 buttons", p1 == 0xFF, f"$00F0=${p1:02X} (expected $FF)")

        #Port 2 is independent
        c.tool("set_controller", {"port": 2, "buttons": ["b"]})
        c.tool("run_frames", {"frames": 5, "timeout_ms": 15000})
        p1, p2, _ = joypad_bytes(c)
        ok("port 2 independent", p1 == 0xFF and p2 == 0x02, f"p1=${p1:02X} p2=${p2:02X}")
        c.tool("release_controller", {"port": 2})

        #release_controller lets go
        c.tool("release_controller", {"port": 1})
        c.tool("run_frames", {"frames": 5, "timeout_ms": 15000})
        p1, p2, _ = joypad_bytes(c)
        ok("release_controller", p1 == 0 and p2 == 0, f"p1=${p1:02X} p2=${p2:02X}")

        #Empty button list also releases
        c.tool("set_controller", {"port": 1, "buttons": ["select"]})
        c.tool("set_controller", {"port": 1, "buttons": []})
        c.tool("run_frames", {"frames": 5, "timeout_ms": 15000})
        p1, _, _ = joypad_bytes(c)
        ok("empty button list releases", p1 == 0, f"$00F0=${p1:02X}")

        #hold_frames auto-releases after the tool has advanced those frames
        r = c.tool("set_controller", {"port": 1, "buttons": ["a"], "hold_frames": 5,
                                      "timeout_ms": 15000})
        ok("set_controller hold_frames", r.get("frames_run", 0) >= 5, str(r)[:160])
        p1, _, _ = joypad_bytes(c)
        ok("hold_frames released the button", p1 == 0, f"$00F0=${p1:02X} (expected $00)")

        #The press is sampled by the game *during* the hold window. The tool
        #advances hold_frames itself and returns once they are over, so check the
        #ROM's sticky byte: zero it, tap Right for 5 frames, and the game must
        #have recorded the press even though the button is released again now.
        c.tool("write_memory", {"memory_type": "internal_ram", "address": 0xF3, "bytes": "00"})
        ok("cleared the sticky byte", read_byte(c, 0xF3) == 0)
        r = c.tool("set_controller", {"port": 1, "buttons": ["right"], "hold_frames": 5,
                                      "timeout_ms": 15000})
        ok("tap: hold_frames=5", r.get("frames_run", 0) >= 5, str(r)[:160])
        sticky, p1 = read_byte(c, 0xF3), read_byte(c, 0xF0)
        ok("press sampled during the hold window", sticky == 0x80 and p1 == 0x00,
           f"sticky=${sticky:02X} (expected $80), held now=${p1:02X} (expected $00)")
        c.tool("release_controller", {"port": 1})

        #Input keeps working across a soft reset...
        c.tool("reset", {})
        c.tool("set_controller", {"port": 1, "buttons": ["a"]})
        c.tool("run_frames", {"frames": 10, "timeout_ms": 15000})
        p1, _, _ = joypad_bytes(c)
        ok("input survives soft reset", p1 == 0x01, f"$00F0=${p1:02X} (expected $01)")
        c.tool("release_controller", {"port": 1})

        #...across a power cycle (the core builds a brand new console)...
        c.tool("reset", {"mode": "power_cycle"})
        c.tool("set_controller", {"port": 1, "buttons": ["b"]})
        c.tool("run_frames", {"frames": 10, "timeout_ms": 15000})
        p1, _, _ = joypad_bytes(c)
        ok("input survives power cycle", p1 == 0x02, f"$00F0=${p1:02X} (expected $02)")
        c.tool("release_controller", {"port": 1})

        #...and across unload + load of another ROM and back
        c.tool("unload_rom", {})
        c.tool("load_rom", {"path": os.path.join(TESTS, "red.nes")})
        c.tool("run_frames", {"frames": 3, "timeout_ms": 15000})
        c.tool("load_rom", {"path": NES_ROM})
        c.tool("set_controller", {"port": 1, "buttons": ["up"]})
        c.tool("run_frames", {"frames": 10, "timeout_ms": 15000})
        p1, _, _ = joypad_bytes(c)
        ok("input survives rom reload", p1 == 0x10, f"$00F0=${p1:02X} (expected $10)")
    finally:
        rc = c.close()
        ok("nes: clean exit", rc == 0, f"rc={rc}")


def console_battery(label, rom, console, port0_buttons):
    print(f"\n== {label} ({console}) ==")
    c = Client()
    try:
        initialize(c)
        ld = c.tool("load_rom", {"path": rom})
        ok(f"{console}: load_rom", "ERR" not in ld, str(ld)[:160])
        ok(f"{console}: console type", ld.get("rom", {}).get("console_type") == console,
           str(ld.get("rom", {}).get("console_type")))
        c.tool("run_frames", {"frames": 30, "timeout_ms": 25000})

        ok(f"{console}: nothing pressed initially", lua_pressed(c, 0) == set(),
           str(lua_pressed(c, 0)))

        r = c.tool("set_controller", {"port": 1, "buttons": list(port0_buttons)})
        ok(f"{console}: set_controller", "ERR" not in r, str(r)[:160])
        c.tool("run_frames", {"frames": 5, "timeout_ms": 25000})
        pressed = lua_pressed(c, 0)
        ok(f"{console}: console sees {sorted(port0_buttons)}", port0_buttons <= pressed,
           f"pressed={sorted(pressed)}")

        c.tool("release_controller", {"port": 1})
        c.tool("run_frames", {"frames": 5, "timeout_ms": 25000})
        pressed = lua_pressed(c, 0)
        ok(f"{console}: release_controller", port0_buttons.isdisjoint(pressed),
           f"pressed={sorted(pressed)}")
    finally:
        rc = c.close()
        ok(f"{console}: clean exit", rc == 0, f"rc={rc}")


def main():
    if not os.path.isfile(BIN):
        print(f"server binary not found: {BIN} (run 'make' first)")
        sys.exit(1)

    with open(NES_ROM, "wb") as f:
        f.write(make_input_test_rom.build_rom())
    red = os.path.join(TESTS, "red.nes")
    if not os.path.isfile(red):
        import make_test_rom
        with open(red, "wb") as f:
            f.write(make_test_rom.build_rom())

    shutil.rmtree(HOME, ignore_errors=True)
    os.makedirs(os.path.join(HOME, "Firmware"), exist_ok=True)
    bios = os.path.join(TESTS, "gba-bios.bin")
    if os.path.isfile(bios):
        shutil.copy(bios, os.path.join(HOME, "Firmware", "gba_bios.bin"))

    nes_battery()

    #Real games: only run when the ROM fixtures are present (e2e_test.py assets)
    snes_rom = os.path.join(TESTS, "snes-rom.zip")
    if os.path.isfile(snes_rom):
        console_battery("SNES / Street Fighter II", snes_rom, "snes", {"start", "y"})
    gba_rom = os.path.join(TESTS, "gba-rom.zip")
    if os.path.isfile(gba_rom) and os.path.isfile(bios):
        console_battery("GBA / SSFIIT Turbo Revival", gba_rom, "gba", {"a", "l"})

    print(f"\n== INPUT TEST PASSED ({passed} checks) ==")


if __name__ == "__main__":
    main()
